name: conferencial_app
services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: temporary
      POSTGRES_DB: conference_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d conference_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  conferencial:
    build: ./conferencial/
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/conference_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: temporary
      SPRING_FLYWAY_URL: jdbc:postgresql://host.docker.internal:5432/conference_db
      SPRING_FLYWAY_PASSWORD: temporary
      SPRING_FLYWAY_USER: admin
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: AdminPassword
    ports:
      - "9889:80"
